### ISSUE TITLE
Issue with running a template based project

### ISSUE THREAD

**Issue by zygon4** [onyx-platform/onyx-template#71]
I'm running into a Clojure schema validation failure when I attempt to run an onyx-template project. The project had no modifications.  It fails when calling to start peer. Here's the big ol' debug log.:

> [fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying... 
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting media driver with threading mode: shared .
                    Use -t to supply an alternative threading mode.
Launched the Media Driver. Blocking forever...
Starting peer-group
Exception in thread "main" clojure.lang.ExceptionInfo: Value does not match schema: {:onyx/tenancy-id (not (matches-some-precondition? nil))} {:type :schema.core/error, :schema {#schema.core.OptionalKey{:k :ony$.peer/trigger-timer-resolution} (pred deprecated-key?), #schema.core.OptionalKey{:k :onyx.peer/storage.s3.multipart-copy-part-size} Int, #schema.core.OptionalKey{:k :onyx.bookkeeper/client-timeout} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.bookkeeper/read-batch-size} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.zookeeper/backoff-base-sleep-time-ms} Int, #schema.core.OptionalKey{:k :onyx.pe$r/stop-task-timeout-ms} Int, #schema.core.OptionalKey{:k :onyx.bookkeeper/write-batch-backoff} (constrained Int pos?), :onyx/tenancy-id (cond-pre Uuid (pred onyx.schema/fn--12244)), #schema.core.OptionalKey{:k $onyx.bookkeeper/ledger-password} java.lang.String, #schema.core.OptionalKey{:k :onyx.peer/job-not-ready-back-off} Int, #schema.core.OptionalKey{:k :onyx.peer/coordinator-barrier-period-ms} (constrained Int pos?$, #schema.core.OptionalKey{:k :onyx.task-scheduler.colocated/only-send-local?} java.lang.Boolean, #schema.core.OptionalKey{:k :onyx.peer/publisher-liveness-timeout-ms} (constrained Int pos?), #schema.core.Optio$alKey{:k :onyx.peer/subscriber-liveness-timeout-ms} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.peer/storage.s3.multipart-copy-threshold} Int, #schema.core.OptionalKey{:k :onyx.messaging.aeron/wri$e-buffer-size} (pred deprecated-key?), #schema.core.OptionalKey{:k :onyx.peer/coordinator-max-sleep-ms} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.messaging/short-circuit-buffer-size} Int, #schem$.core.OptionalKey{:k :onyx.bookkeeper/ledger-ensemble-size} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.peer/tags} [Keyword], #schema.core.OptionalKey{:k :onyx.peer/drained-back-off} Int, #schema.$ore.OptionalKey{:k :onyx.peer/fn-params} Any, #schema.core.OptionalKey{:k :onyx.peer/retry-start-interval} Int, #schema.core.OptionalKey{:k :onyx.rocksdb.filter/num-buckets} (constrained Int pos?), #schema.core$OptionalKey{:k :onyx.messaging/decompress-fn} (pred deprecated-key?), #schema.core.OptionalKey{:k :onyx.peer/storage.s3.accelerate?} java.lang.Boolean, #schema.core.OptionalKey{:k :onyx.monitoring/config} (mayb$ {Any Any}), #schema.core.OptionalKey{:k :onyx.rocksdb.filter/num-ids-per-bucket} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.query.server/ip} java.lang.String, #schema.core.OptionalKey{:k :onyx.p$er/storage.timeout} Int, #schema.core.OptionalKey{:k :onyx.messaging.aeron/publication-creation-timeout} (pred deprecated-key?), #schema.core.OptionalKey{:k :onyx.query/server?} java.lang.Boolean, #schema.core.$ptionalKey{:k :onyx.bookkeeper/ledger-id-written-back-off} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.peer/storage} (enum :zookeeper :s3), #schema.core.OptionalKey{:k :onyx.rocksdb.filter/peer-bl$ck-cache-size} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.peer/peer-not-ready-back-off} Int, #schema.core.OptionalKey{:k :onyx.messaging/compress-fn} (pred deprecated-key?), #schema.core.Optional$ey{:k :onyx.peer/outbox-capacity} Int, #schema.core.OptionalKey{:k :onyx.messaging/external-addr} java.lang.String, #schema.core.OptionalKey{:k :onyx.messaging.aeron/subscriber-count} (pred deprecated-key?), #s$hema.core.OptionalKey{:k :onyx.log/config} (maybe {Any Any}), #schema.core.OptionalKey{:k :onyx.peer/storage.s3.encryption} (enum :aes256 :none), #schema.core.OptionalKey{:k :onyx.zookeeper/backoff-max-retries} Int, #schema.core.OptionalKey{:k :onyx/id} (pred deprecated-key?), :onyx.messaging/impl (enum :aeron :atom), #schema.core.OptionalKey{:k :onyx.peer/storage.s3.bucket} java.lang.String, #schema.core.OptionalKey{$k :onyx.query.server/port} Int, #schema.core.OptionalKey{:k :onyx.peer/state-log-impl} Keyword, #schema.core.OptionalKey{:k :onyx.peer/join-failure-back-off} Int, #schema.core.OptionalKey{:k :onyx.rocksdb.filte$/block-size} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.rocksdb.filter/rotation-check-interval-ms} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.peer/initial-sync-backoff-ms} Int, #sc$ema.core.OptionalKey{:k :onyx.peer/storage.s3.endpoint} java.lang.String, #schema.core.OptionalKey{:k :onyx.rocksdb.filter/compression} (enum :zlib :bzip2 :snappy :lz4hc :lz4 :none), #schema.core.OptionalKey{:k :onyx.messaging/peer-port} Int, #schema.core.OptionalKey{:k :onyx.zookeeper/prepare-failure-detection-interval} Int, #schema.core.OptionalKey{:k :onyx.peer/storage.s3.auth.access-key} java.lang.String, #schema.$ore.OptionalKey{:k :onyx.peer/state-filter-impl} Keyword, #schema.core.OptionalKey{:k :onyx.messaging.aeron/embedded-driver?} java.lang.Boolean, #schema.core.OptionalKey{:k :onyx.peer/idle-max-sleep-ns} (constr$ined Int pos?), :zookeeper/address java.lang.String, #schema.core.OptionalKey{:k :onyx.bookkeeper/write-buffer-size} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.bookkeeper/write-batch-size} (const$ained Int pos?), #schema.core.OptionalKey{:k :onyx.peer.metrics/lifecycles} [(enum :lifecycle/offer-barrier-status :lifecycle/after-batch :lifecycle/unblock-subscribers :lifecycle/recover-input :lifecycle/check$oint-output :lifecycle/seal-barriers? :lifecycle/after-read-batch :lifecycle/check-publisher-heartbeats :lifecycle/checkpoint-input :lifecycle/write-batch :lifecycle/apply-fn :lifecycle/offer-barriers :lifecycl$/offer-heartbeats :lifecycle/assign-windows :lifecycle/before-batch :lifecycle/read-batch :lifecycle/recover-output :lifecycle/checkpoint-state :lifecycle/after-apply-fn :lifecycle/input-poll-barriers :lifecycl$/next-iteration :lifecycle/recover-state :lifecycle/prepare-batch :lifecycle/poll-recover)], #schema.core.OptionalKey{:k :onyx.rocksdb.filter/base-dir} java.lang.String, #schema.core.OptionalKey{:k :onyx.messag$ng.aeron/poll-idle-strategy} (pred deprecated-key?), :onyx.peer/job-scheduler (pred keyword-namespaced?), #schema.core.OptionalKey{:k :onyx.peer/storage.s3.auth.secret-key} java.lang.String, #schema.core.Option$lKey{:k :onyx.messaging.aeron/offer-idle-strategy} (pred deprecated-key?), #schema.core.OptionalKey{:k :onyx.peer/storage.s3.auth-type} (enum :config :provider-chain), #schema.core.OptionalKey{:k :onyx.peer/hea$tbeat-ms} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.peer/inbox-capacity} Int, Any Any, #schema.core.OptionalKey{:k :onyx.messaging.aeron/embedded-media-driver-threading} (enum :shared-network :s$ared :dedicated), #schema.core.OptionalKey{:k :onyx.peer/storage.s3.region} java.lang.String, #schema.core.OptionalKey{:k :onyx.zookeeper/backoff-max-sleep-time-ms} Int, #schema.core.OptionalKey{:k :onyx.window$ng/min-value} Int, #schema.core.OptionalKey{:k :onyx.bookkeeper/client-throttle} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.peer/idle-min-sleep-ns} (constrained Int pos?), :onyx.messaging/bind-ad$r java.lang.String, #schema.core.OptionalKey{:k :onyx.messaging/allow-short-circuit?} java.lang.Boolean, #schema.core.OptionalKey{:k :onyx.rocksdb.filter/bloom-filter-bits} (constrained Int pos?), #schema.core.OptionalKey{:k :onyx.bookkeeper/ledger-quorum-size} (constrained Int pos?)}, :value {:onyx/tenancy-id nil, :onyx.messaging/allow-short-circuit? true, :onyx.messaging/impl :aeron, :onyx.log/config {:level :info}, 
:onyx.messaging/peer-port 40200, :zookeeper/address "zookeeper:2181", :onyx.peer/job-scheduler :onyx.job-scheduler/balanced, :onyx.messaging.aeron/embedded-driver? false, :onyx.peer/zookeeper-timeout 60000, :ony
x.messaging/bind-addr "localhost"}, :error {:onyx/tenancy-id (not (matches-some-precondition? nil))}}
        at schema.core$validator$fn__11183.invoke(core.clj:155)
        at schema.core$validate.invokeStatic(core.clj:164)
        at schema.core$validate.invoke(core.clj:159)
        at onyx.static.validation$validate_peer_config.invokeStatic(validation.clj:250)
        at onyx.static.validation$validate_peer_config.invoke(validation.clj:249)
        at onyx.api$start_peer_group.invokeStatic(api.clj:499)
        at onyx.api$start_peer_group.invoke(api.clj:495)
        at lib_onyx.peer$start_peer.invokeStatic(peer.clj:9)
        at lib_onyx.peer$start_peer.invoke(peer.clj:4)
        at onyx_hackathon.core$_main.invokeStatic(core.clj:77)
        at onyx_hackathon.core$_main.doInvoke(core.clj:67)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at onyx_hackathon.core.main(Unknown Source)
opt/run_peer.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

So something with that peer config/environment isn't happy. I'm not a Clojure schema expert - does anyone else fine this reproducible? I built the project with:

> Leiningen 2.8.0 on Java 1.8.0_141 OpenJDK 64-Bit Server VM

and am launching it via the docker and the Dockerfile that lein <stuff> -- +docker generates.

**Comment by zygon4** [comment]
Issue:  ":onyx/tenancy-id" being passed into peer/start-peer was nil. If it's supposed to be picked up from somewhere, it's not. I hacked it to be "1" and the peer started up.

**Comment by lbradstreet** [comment]
Thanks. Sorry that the schema errors are a little inscrutable.
